services:
  - type: web
    name: uber-clone-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DB_CONNECT
        sync: false
      - key: JWT_SECRET
        sync: false
